# Pizza Liking Prediction using kNN

In [ ]:
Name:S.Deepa
Rollno:225229107
lab02

# step 1: Prepare your dataset

In [5]:
import pandas as pd
df=pd.read_csv('pizza.csv')
print(df)

   age  weight  likepizza
0   50      65          0
1   20      55          1
2   15      40          1
3   70      65          0
4   30      70          1
5   75      60          0


In [20]:
import pandas as pd
df1=pd.read_csv('pizza_test.csv')
print(df1)

   age  weight  likePizza
0   48      68          1
1   35      45          1
2   15      40          0
3   55      65          0


# step 2:import dataset

In [6]:
df.head()

age  weight  likepizza
0   50      65          0
1   20      55          1
2   15      40          1
3   70      65          0
4   30      70          1

In [8]:
df.head()

age  weight  likepizza
0   50      65          0
1   20      55          1
2   15      40          1
3   70      65          0
4   30      70          1

In [3]:
df.shape

(6, 3)

In [9]:
df1.shape

(4, 3)

In [10]:
df.columns

Index(['age', 'weight', 'likepizza'], dtype='object')

In [11]:
df1.columns

Index(['age', 'weight', 'likePizza'], dtype='object')

In [21]:
 df.info

<bound method DataFrame.info of    age  weight  likepizza
0   50      65          0
1   20      55          1
2   15      40          1
3   70      65          0
4   30      70          1
5   75      60          0>

In [13]:
df1.info

<bound method DataFrame.info of    age  weight  likePizza
0   48      68          1
1   35      45          1
2   15      40          0
3   55      65          0>

# step 3:visualize relationships

In [41]:
import matplotlib.pyplot as plt
import seaborn as sns



AttributeError: module 'seaborn' has no attribute 'scatterplot'

# step 4:Prepare x matrix and y vector

In [26]:
X=pd.DataFrame(df)
cols=[0,1]
X=X[X.columns[cols]]


In [29]:
y=df['likepizza'].values

# step 5: Examine x and y

In [31]:
X

age  weight
0   50      65
1   20      55
2   15      40
3   70      65
4   30      70
5   75      60

In [32]:
type(X)

pandas.core.frame.DataFrame

In [34]:
y

array([0, 1, 1, 0, 1, 0], dtype=int64)

In [35]:
type(y)

numpy.ndarray

# step 6:Model building

In [36]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=2)
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=2, p=2,
           weights='uniform')

# step 7:Model testing

In [38]:
knn.predict(X)

array([0, 1, 1, 0, 1, 0], dtype=int64)

In [42]:
a=[25,50]
knn.predict([a])


array([1], dtype=int64)

In [43]:
b=[60,60]
knn.predict([b])

array([0], dtype=int64)

# step 8:Change n_neighbors = 3

In [44]:
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X,y)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [45]:
c=[25,50]
knn.predict([c])


array([1], dtype=int64)

In [46]:
d=[60,60]
knn.predict([d])

array([0], dtype=int64)

In [47]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X,y)



KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [48]:

y_pred=knn.predict(X)
y_pred

array([0, 1, 1, 0, 1, 0], dtype=int64)

# step 10:Accuracy function

In [49]:
def accuracy(actual,pred):
    return sum(actual==pred)/float(actual.shape[0])


# step 11:Find accuracy

In [50]:
accuracy_score=accuracy(y,y_pred)
accuracy_score


1.0

In [53]:
import pandas as pd
df1=pd.read_csv('pizza_test.csv')
print(df1)

   age  weight  likePizza
0   48      68          1
1   35      45          1
2   15      40          0
3   55      65          0


In [54]:
df1.head()

age  weight  likePizza
0   48      68          1
1   35      45          1
2   15      40          0
3   55      65          0

In [55]:
df1.shape

(4, 3)

In [56]:
df1.columns

Index(['age', 'weight', 'likePizza'], dtype='object')

In [57]:
df1.info

<bound method DataFrame.info of    age  weight  likePizza
0   48      68          1
1   35      45          1
2   15      40          0
3   55      65          0>

In [59]:
x=pd.DataFrame(df1)
cols=[0,1]
x=x[x.columns[cols]]


In [60]:
x

age  weight
0   48      68
1   35      45
2   15      40
3   55      65

In [63]:
Y=df1['likePizza'].values
Y

array([1, 1, 0, 0], dtype=int64)

In [64]:
from sklearn.neighbors import KNeighborsClassifier
test=KNeighborsClassifier(n_neighbors=2)
test.fit(x,Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=2, p=2,
           weights='uniform')

In [65]:
Y_pred=test.predict(x)
Y_pred


array([0, 0, 0, 0], dtype=int64)

In [67]:
import numpy as np
Y=np.array([1,1,0,0])
Y

array([1, 1, 0, 0])

In [69]:
Y_test=accuracy(Y,Y_pred)
Y_test


0.5

# step 13: Find best value for k

In [74]:
scores=[]
for k in range(1,4):
    kn=KNeighborsClassifier(n_neighbors=k)
    kn.fit(x,Y)
    kn.predict(x)
    y_test=kn.predict(x)
    a=accuracy(Y,Y_pred)
    scores.append((k,a))
    
print(scores)

[(1, 0.5), (2, 0.5), (3, 0.5)]


# step 14: Accuracy_score function

In [75]:
from sklearn.metrics import accuracy_score

In [77]:
accuracy_score(Y,Y_pred)

0.5